/**
 * This Library was originally written by RedMagic Electric Drivetrain Studio in 2025
 * Notes are generated by doubao ai
 * Module for stm32l432xx hi2c3
 * Official Documentation Routines
 */

#ifndef __MAX_30205_H_
#define __MAX_30205_H_

#include "stm32l432xx.h"
#include "main.h"

#define MAX30205_ADDR       		0x90
#define MAX30205_TEMP				    0x00  
#define MAX30205_CONFIG					0x01  
#define MAX30205_THYST          0x02  
#define MAX30205_TOS            0x03  

//功能选择
void MAX30205_Init(void);
void MAX30205_Shutdown(void);
void MAX30205_OneShotMode(void);
float MAX30205_GetTemperature(void);

//iic模式选择
void max30205_i2c_readBytes(uint8_t address, uint8_t reg, uint8_t* data, uint8_t size);
uint8_t max30205_i2c_readByte(uint8_t address, uint8_t reg);
uint8_t max30205_i2c_writeByte(uint8_t address, uint8_t reg, uint8_t value) ;

#endif
