/**
 * This Library was originally written by RedMagic Electric Drivetrain Studio in 2025
 * Notes are generated by doubao ai
 * Module for stm32l432xx and max30102 SPO2 receive
 * Official Documentation Routines
 */

#ifndef __BLOOD_H
#define __BLOOD_H

#include <stdint.h>
#include <stdbool.h>

/* 配置参数 */
#define BLOOD_SAMPLE_RATE 100      // 采样率(Hz)
#define BLOOD_BUFFER_SIZE 100      // 数据缓冲区大小
#define BLOOD_MIN_SPO2 70          // 最小血氧值
#define BLOOD_MAX_SPO2 100         // 最大血氧值

/* 错误码定义 */
typedef enum {
    BLOOD_OK = 0,                 // 正常
    BLOOD_ERROR_INIT = -1,        // 初始化错误
    BLOOD_ERROR_READ = -2,        // 读取数据错误
    BLOOD_ERROR_CALC = -3,        // 计算错误
} BloodError;

/* 测量结果结构体 */
typedef struct {
    uint8_t spo2;                 // 血氧饱和度(%)
    uint8_t heartRate;            // 心率(次/分钟)
    bool pulseDetected;           // 是否检测到脉搏
    uint32_t timestamp;           // 测量时间戳
} BloodResult;

/* 初始化血氧测量模块 */
BloodError Blood_Init(void);

/* 读取最新的血氧和心率数据 */
BloodError Blood_Read(BloodResult *result);

/* 更新传感器数据(内部使用) */
void Blood_Update(uint32_t red, uint32_t ir);

/* 重置测量状态 */
void Blood_Reset(void);

#endif /* __BLOOD_H */
